# Generated by Django 4.1.7 on 2023-03-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProjectstones4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Amount',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='idnumber',
            field=models.IntegerField(blank=True),
        ),
    ]
