# Generated by Django 4.1.7 on 2023-03-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProjectstones4', '0002_employees_amount_alter_employees_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='idnumber',
            new_name='number',
        ),
    ]
